#! /usr/bin/python

# releasechecker.py
#
#  Copyright (c) 2010 Jonathan Thomas <echidnaman@kubuntu.org>
#
#  Author: Jonathan Thomas <echidnaman@kubuntu.org>
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License as
#  published by the Free Software Foundation; either version 2 of
#  the License or (at your option) version 3 or any later version
#  accepted by the membership of KDE e.V. (or its successor approved
#  by the membership of KDE e.V.), which shall act as a proxy
#  defined in Section 14 of version 3 of the license.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

import urllib
import sys

if __name__ == "__main__":

  releaseHandle = urllib.urlopen('http://ftp.debian.org/debian/dists/stable/Release')
  localHandle= open('/etc/os-release', 'r')

  releases = ["squeeze","wheezy","jessie","sid"]

  linesLocal = localHandle.readlines()
  lines = releaseHandle.readlines()

  localRelease = linesLocal[0].split()[2]
  localRelease = localRelease[:-1]

  if (localRelease in releases) == False:
    localRelease = localRelease.split('/')[0]
  
  print localRelease
  print lines[4].split()[1]
  
  releaseHandle.close()
  localHandle.close()
  
  if releases.index(localRelease) < releases.index(lines[4].split()[1]):
    sys.exit(0)
  else:
    sys.exit(1)

